### ISSUE TITLE
raise Uncaught PDOException after install github-login extension

### ISSUE THREAD

**Issue by Folyd** [flarum/core#1204]
## Bug report
- Version of Flarum: 0.1.0-beta.6
- Website URL where the bug is visible: 
- The webserver you are running: nginx
- PHP version: 7.1.5
- Hosted environment: docker

## PHP version
```
# docker exec -ti ubuntu_flarum_1 php --version
PHP 7.1.5 (cli) (built: May 26 2017 18:14:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.5, Copyright (c) 1999-2017, by Zend Technologies
```

## Flarum info
I run flarum in docker, the image from [mondediefr/docker-flarum](https://github.com/mondediefr/docker-flarum)

## Here are `docker-compose.yml`
```yml
version: "3"
services:
  flarum:
    image: mondedie/docker-flarum:0.1.0-beta.6-stable
    ports:
      - "8888:8888"
    depends_on:
      - mysqldb
    environment:
      - FORUM_URL=https://forum.domain.tld
      - DB_PASS=flarum_password
    volumes:
      - /mnt/docker/flarum/assets:/flarum/app/assets
      - /mnt/docker/flarum/extensions:/flarum/app/extensions

  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=flarum_password
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=flarum

```

## Log files

```
flarum_1   | [INFO] Flarum already installed, init app...
flarum_1   |
flarum_1   | Fatal error: Uncaught PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name does not resolve in /flarum/app/vendor/illuminate/database/Connectors/Connector.php:55
flarum_1   | Stack trace:
flarum_1   | #0 /flarum/app/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('mysql:host=mari...', 'flarum', 'flarum', Array)
flarum_1   | #1 /flarum/app/vendor/illuminate/database/Connectors/MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=mari...', Array, Array)
flarum_1   | #2 /flarum/app/vendor/illuminate/database/Connectors/ConnectionFactory.php(60): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
flarum_1   | #3 /flarum/app/vendor/illuminate/database/Connectors/ConnectionFactory.php(49): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
flarum_1   | #4 /flarum/app/vendor/flarum/core/src/Database/DatabaseServiceProvider.php(29): Illuminate\Database\Connectors\ConnectionFactory->make(Array)
flarum_1   | #5 /flarum/app/vendor/illuminate/container/Container.php(738): Flarum\Databa in /flarum/app/vendor/illuminate/database/Connectors/Connector.php on line 55
flarum_1   | [INFO] No installed extensions
flarum_1   | [INFO] Init done, launch flarum...
```
