### ISSUE TITLE
Stick the left menu

### ISSUE THREAD

**Issue by therealsujitk** [flarum/core#1969]
### Feature Request

I feel this request is pretty small. I think it would be better if,  the left menu (having all the tags) is kept stationary , even when the page is being scrolled.

**Comment by irkmix** [comment]
No

**Comment by therealsujitk** [comment]
@irkmix No, as in bad idea or, no as in it isn't a small request?

**Comment by tankerkiller125** [comment]
The following less inside the "Custom Styles" setting under appears should give you approximatly what your looking for.


```less
.sideNav {
    @media @desktop-up {
        position: fixed;
    }
}

.sideNavOffset {
    @media @desktop-up {
        margin-left: 20%;
    }
}

```
