### ISSUE TITLE
Tag Choosing Position have Offset.

### ISSUE THREAD

**Issue by Littlegolden** [flarum/core#2040]
## Bug Report

**Current Behavior**
When a primary tag is selected and a secondary tag is selected, the position of the label row is shifted.

**Steps to Reproduce**
1. Go to 'Home Page'
2. Click on 'Creat a discussion'
3. Choose tags ( one primary tag and a secondary tag )
4. You will see their position will offset.

**Screenshots**
https://drive.google.com/open?id=10QtthGn8Ws-lMB3FLaIODpIwhvhZaecX

**Environment**
- Flarum version: beta.11.1
- Website URL: http://discuss.flarum.org
- Browser: Chrome 80.0.3987.122

**Possible Solution**
```css
.TagDiscussionModal .Modal-content,
.TagDiscussionModal .TagsInput{
    overflow: unset;
}
```
