### ISSUE TITLE
[Mobile] Slidable underneath discussion controls alignment

### ISSUE THREAD

**Issue by SychO9** [flarum/core#2329]
## Bug Report

**Current Behavior**
On small touchscreens, if you slide a discussion to open the controls dropdown, you will notice the controls dropdown button aligned to the left side, making it hardly if ever noticeable.

**Steps to Reproduce**
1. Go to the discussion list
2. Slide a discussion to the left

**Expected Behavior**
I believe it is supposed to be on the right side, the element itself does have a `Slidable-underneath--right` class, so the initial implementation probably was aimed to do that.

**Screenshots**
<img src="https://user-images.githubusercontent.com/20267363/94729995-7502f480-035a-11eb-9541-5fd82eafe684.png" width=426 alt="screenshot">

**Environment**
- Flarum version: https://github.com/flarum/core/commit/86d4bf0214467807d1fefd7a8adb4a29031d0f1c
- Browser: Chrome 84

**Possible Solution**
```less
    .Slidable-underneath {
      width: 100%;
    }
    .Slidable-underneath--right {
      left: unset;
    }
```
![Screenshot from 2020-09-30 20-32-04](https://user-images.githubusercontent.com/20267363/94731224-59005280-035c-11eb-848b-9fbeb6da8bdd.png)
