### ISSUE TITLE
Author badge css not loaded unless triggered from the discussion list

### ISSUE THREAD

**Issue by justoverclockl** [flarum/core#2750]
Discussion for details:
https://discuss.flarum.org/d/26007-adding-author-label-to-posts/36

CSS class it relies on is not loaded unless triggered from the discussion list.

here the code we actually use:

```less
div.PostStream div.PostStream-item:not(:first-child) article.CommentPost.Post.Post--by-start-user .Post-header h3:after {
  content: "Author";
  background: #F05D1D;
  border-radius: 4px;
  padding-left: 10px;
  padding-right: 10px;
  color: #fff;
  margin-left: 14px;
}
```
