### ISSUE TITLE
Over-specified selectors in ExtensionPage.less

### ISSUE THREAD

**Issue by SychO9** [flarum/core#2791]
Came across these (we missed them before) while playing around with the admin dashboard design, `ExtensionPage.less` has too much over-specification making customization quite difficult as it forces designers to over-specify a lot more to override the default styles. It's also good practice not to over-specify.

Examples of the compiled CSS code:
```css
.ExtensionPage .ExtensionPage-header .ExtensionPage-headerTopItems, .ExtensionPage .ExtensionPage-permissions-header .ExtensionPage-headerTopItems {
    margin-left: auto;
}

.ExtensionPage .ExtensionPage-header .ExtensionPage-headerItems, .ExtensionPage .ExtensionPage-permissions-header .ExtensionPage-headerItems {
    padding: 15px 0;
    display: flex;
    align-items: center;
    flex-wrap: wrap;
}
```

both can just be
```css
.ExtensionPage-headerTopItems, .ExtensionPage-permissions-headerTopItems {
    margin-left: auto;
}

.ExtensionPage-headerItems {
    padding: 15px 0;
    display: flex;
    align-items: center;
    flex-wrap: wrap;
}
```
