### ISSUE TITLE
Translation of Tags

### ISSUE THREAD

**Issue by amdad** [flarum/core#527]
We already have in English
```yaml
 discussion_tagged_post:
    one: "{username} {action} tag."
    other: "{username} {action} tags."
  added_tags: "added the {tags}"
  removed_tags: "removed the {tags}"
```
Unfortunately, strings logic in sentence is too strict. I've tried in many ways, but I cannot form correct phrase in my language with this.

I need  pluralization for {action} part.
 
It would be like: 
Of course **this is not English** grammar/logic. Just example of structure in my localization.
```yaml
 discussion_tagged_post:
    one: "{username} {action}."
    other: "{username} {action}."
  added_tags:
    one: "add tag {tags}"
    two: "add tags  {tags}"
    other: ...
  removed_tags:
    one: "remove tag {tags}"
    two: "remove tags  {tags}"
    other: ...
``` 

**Edit :** Removed whole first proposed solution.

**Comment by amdad** [comment]
Update, it's even worse if we want to have full sentence of added and removed tags like you in English. I've updated example above. I'm sorry to make such mess. But Flarum is step ahead of being best translated Forum on this planet. If we did this and add genders.

**Comment by amdad** [comment]
Oh, after a while of thinking first solution wold be too messy. So I left only second solution as proposal of solution.

**Comment by tobscure** [comment]
Gotcha, looks doable. Pinging @dcsjapan in case he has any thoughts.

**Comment by amdad** [comment]
Uff, nice to hear it's not too big problem.

Please remember about Gender plugin and translation support. It's **really** needed here. Should I create another issue for this? Anytime soon?

**Comment by tobscure** [comment]
Another issue would be good. We'll try and get it in within a few weeks.

**Comment by dcsjapan** [comment]
> Pinging @dcsjapan in case he has any thoughts.

Thanks @tobscure ... of course I haven't looked at the Tags extension at all yet, and am still trying to get up to speed on YML. But I wondering if it's really necessary to move the "tags" out of the first string.

Would this sort of thing be possible?
```
discussion_tagged_post:
    one: "{username} {action} tag."
    other: "{username} {action} tags."
  added_tags: "added the {tags}"
      one: "added(sing) the {tags}"
      two: "added(dual) the {tags}"
      other: "added(plur) the {tags}"
  removed_tags:
      one: "removed(sing) the {tags}"
      two: "removed(dual) the {tags}"
      other: "removed(plur) the {tags}"
```
In other words, is the number context applied recursively?

If it isn't, then what @amdad proposes looks great.

(I'm guessing the first proposal involved abstracting the word "tag" from all the {action} strings?)

**Comment by amdad** [comment]
Yes, first proposal was about placing {username} and {tags} in one string.
But this caused problem when it comes to mixed content. When Someone add and remove tags at once. Then I realized separating strings is much flexible.

Like your example is OK, but in this line is error:

```yaml
  added_tags: ~~"added the {tags}"~~ // This should be removed
      one: "added(sing) the {tags}"
      two: "added(dual) the {tags}"
      other: "added(plur) the {tags}"
```

I used, one, two and other because of my localization working on this.

```javascript
app.translator.plural = function(count) {
  if (count == 1) {
    return 'one';
  }
  else if (count > 1 && count < 5) {
        return 'two';
  }
  else {
    return 'other';
  }
};
```
And I use this second rule almost everywhere. But rules can be different for each language. Though, I think not much languages have such expanded grammar as mine :)

**Comment by dcsjapan** [comment]
Which language are you localizing for @amdad ?

**Comment by amdad** [comment]
Taking on Chat. Thanks for interest dcsjapan

**Comment by dcsjapan** [comment]
Glad to help!

It seems there's two issues happening at once here:

- Number context needs to be applied to sub-strings so verbs can agree with the objects
- Also, the object needs to come before the verb

I'm thinking that if @tobscure can solve the first problem, the second will take care of itself.

English YML (copied for ease of reference):
```
discussion_tagged_post:
    one: "{username} {action} tag."
    other: "{username} {action} tags."
  added_tags: "added the {tags}"
  removed_tags: "removed the {tags}"
```
Target language:
```
discussion_tagged_post:
    one: "{username} tag(sing) {action}." // Object moved by translator.
    two: "{username} tag(dual) {action}." // Line added by translator.
    other: "{username} tag(plur) {action}." // Object moved by translator.
  added_tags: // String deleted.
      one: "added(sing) tag(sing) {tags}" // Line added by translator.
      two: "added(dual) tag(dual) {tags}" // Line added by translator.
      other: "added(plur) tag(plur) {tags}" // Line added by translator.
  removed_tags: // String deleted.
      one: "removed(sing) tag(sing) {tags}" // Line added by translator.
      two: "removed(dual) tag(dual) {tags}" // Line added by translator.
      other: "removed(plur) tag(plur) {tags}" // Line added by translator.
```
Will this work for you @amdad ?

If so, the English YML is fine as is. The only reason to change it would be if you wanted to generalize the discussion_tagged_post string for use with other things than tags. ;)

**Comment by amdad** [comment]
> Will this work for you @amdad ?

It's not, thats the case.

**Comment by dcsjapan** [comment]
Update after chatting with @tobscure ...

- The code needs to to supply separate "count" values for added_tags and removed_tags as well.
- Use of **punctuate()** needs to be avoided, since some languages don't use "and" to join clauses.
- Instead, it would be best to replace discussion_tagged_post with three strings:
 - One for cases where tags are only added.
 - One for cases where tags are only removed.
 - One for cases where tags are both added and removed.
- The last third one would still need to provide separate "count" values for the added and removed parts.

**Comment by amdad** [comment]
Oh, all was mainly in my first proposal, which I removed.  Because I worry about: 

> The third one would still need to accommodate separate "count" values for the two verbs.

But if this will on board it will be all  great.  Just to be sure, of course, in your arrangement  added_tags: and removed_tags: will allow for full pluralization?

``` yaml
added_tags: 
    one: added {tags} tag 
    two: added {tags} tags
    other: ....
removed_tags:  
   one: ...
   other: ...
```
